# -*- coding: utf-8 -*-
"""
AI Error Explainer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# AI-Powered Error Explainer

This notebook contains a function `ai_answer_traceout` that uses an AI model to analyze and explain Python errors. When an exception occurs, you can call this function to get a detailed explanation and a suggested solution.

## Step 1: Install Dependencies

We only need the `requests` library to make API calls to the AI model provider.
"""

# !pip install -q requests

"""## Step 2: Import Libraries

We'll need `os` to manage API keys, `requests` to call the API, `traceback` to get detailed error information, and `sys` to access exception details.
"""

import os
import sys
import requests
import traceback
import io
import linecache  # <-- Add this import

"""## Step 3: Set Up Your API Key

To use this function, you need an API key from OpenRouter.ai.

1.  Go to [OpenRouter.ai](https://openrouter.ai/) and create an account.
2.  Get your free API key from your settings page.
3.  **In Google Colab, it's best to use secrets management.** Click on the **key icon (🔑)** in the left sidebar, add a new secret named `OPENROUTER_API_KEY`, and paste your key as the value.

This code will attempt to load the key from Colab's secrets.
"""

# Load the API key from Colab's secret manager
try:
    from google.colab import userdata
    OPENROUTER_API_KEY = userdata.get('OPENROUTER_API_KEY')
    os.environ['OPENROUTER_API_KEY'] = OPENROUTER_API_KEY
    print("API Key loaded successfully from Colab secrets.")
except ImportError:
    print("Not in a Colab environment. Please set the OPENROUTER_API_KEY environment variable manually.")
    # For local testing, you can uncomment the next line and paste your key
    # os.environ['OPENROUTER_API_KEY'] = 'YOUR_OPENROUTER_API_KEY_HERE'


"""## Step 4: Configuration

Here, we define all the configurable parts of our tool, such as the API endpoint, model, and default prompt.
"""

AI_CONFIG = {
    "api_key": os.environ.get("OPENROUTER_API_KEY"),
    "api_endpoint": "https://openrouter.ai/api/v1/chat/completions",
    "model_names":  [ # List of models to try in order
        "qwen/qwen3-coder:free",
        "moonshotai/kimi-k2:free",
        "tngtech/deepseek-r1t2-chimera:free"
    ],
}
AI_CONFIG["default_prompt_prefix"]= """
You are an expert Python debugging assistant.
A Python script encountered an error. Please explain the following traceback in a clear,
concise, and friendly manner.

1.  **Identify the Error**: What is the name of the error and what does it mean?
2.  **Locate the Problem**: Pinpoint the exact line of code that caused the error.
3.  **Explain the Cause**: Why did this error happen in this specific context?
4.  **Suggest a Solution**: Provide a corrected code snippet to fix the issue.
Answer in chinese
"""

"""## Step 5: Define the AI Error Explainer Function (Refactored)

This is the core function. It is now refactored to use the configuration and accept optional parameters for a custom prompt and additional context.
"""

def ai_answer_traceout(custom_prompt_prefix=None, additional_info=None, AI_CONFIG=AI_CONFIG):
    """
    Analyzes a Python error traceback using an AI model from OpenRouter.
    This version includes the source code context around the error.
    This function should be called from within an `except` block.

    Args:
        custom_prompt_prefix (str, optional): A custom prompt to use instead of the default one.
        additional_info (str, optional): Optional additional information to provide to the AI.

    Returns:
        str: The AI's explanation of the error and suggested solution.
    """
    # Get the full, formatted traceback string
    exc_type, exc_value, exc_traceback = sys.exc_info()
    error_traceback = "".join(traceback.format_exception(exc_type, exc_value, exc_traceback))

    # --- START OF NEW CODE TO CAPTURE CONTEXT ---
    code_context_str = "Could not extract code context. This may happen in a REPL or with dynamically executed code."
    try:
        tb_summary = traceback.extract_tb(exc_traceback)
        if tb_summary:
            last_frame = tb_summary[-1]
            filename = last_frame.filename
            error_lineno = last_frame.lineno

            # Clear any cached data for the file to ensure we read the latest version
            linecache.checkcache(filename)

            # Define how many lines of context to show before and after
            context_lines = 3
            start_line = max(1, error_lineno - context_lines)
            end_line = error_lineno + context_lines

            lines = []
            for i in range(start_line, end_line + 1):
                line = linecache.getline(filename, i)
                if line:
                    # Add a marker to highlight the exact error line
                    prefix = ">> " if i == error_lineno else "   "
                    lines.append(f"{prefix}{i:4}: {line.rstrip()}")
            
            if lines:
                code_context_str = "\n".join(lines)

    except Exception as e:
        code_context_str = f"An error occurred while extracting code context: {e}"
    # --- END OF NEW CODE ---


    api_key = AI_CONFIG.get("api_key")
    if not api_key:
        return "Error: OPENROUTER_API_KEY is not set."

    prompt_prefix = custom_prompt_prefix if custom_prompt_prefix else AI_CONFIG["default_prompt_prefix"]

    # --- MODIFIED PROMPT ---
    # The prompt now includes the new code_context_str variable
    prompt = f"""
    {prompt_prefix}

    Here is the source code context from the file. The line marked with '>>' is where the error occurred.
    ---
    {code_context_str}
    ---

    And here is the full technical traceback for reference:
    ---
    {error_traceback}
    ---
    """

    if additional_info:
        prompt += f"""
    Here is some additional context that might be helpful:
    ---
    {additional_info}
    ---
    """
    print("*"*100)
    # Print the context being sent to the AI for debugging
    print("Code context being sent to AI:")
    print(code_context_str)
    print("\nFull traceback:")
    print(error_traceback)
    print("*"*100)

    last_error = None
    for model_name in AI_CONFIG["model_names"]:
        print(f"Attempting to use model: {model_name}")
        try:
            response = requests.post(
                url=AI_CONFIG["api_endpoint"],
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json"
                },
                json={
                    "model": model_name,
                    "messages": [
                        {"role": "user", "content": prompt}
                    ]
                }
            )
            response.raise_for_status()
            data = response.json()
            if 'choices' in data and data['choices'] and 'message' in data['choices'][0] and 'content' in data['choices'][0]['message']:
                return data['choices'][0]['message']['content']
            else:
                last_error = f"Error: Unexpected API response format from {model_name}.\nResponse: {response.text}"
                print(last_error)
                continue

        except requests.exceptions.HTTPError as http_err:
            if response.status_code in [429, 502, 503]:
                last_error = f"HTTP Error for {model_name} (Status {response.status_code}): {http_err}"
                print(f"{model_name} failed. Trying next model. Error: {last_error}")
                continue
            else:
                return f"HTTP Error for {model_name} (Status {response.status_code}): {http_err}\nResponse: {response.text}"
        except requests.exceptions.RequestException as req_err:
            last_error = f"API Request Error for {model_name}: {req_err}"
            print(f"{model_name} failed. Trying next model. Error: {last_error}")
            continue
        except Exception as e:
            last_error = f"Unexpected error with {model_name}: {e}"
            print(f"{model_name} failed. Trying next model. Error: {last_error}")
            continue

    return f"All AI models failed.\nLast error: {last_error if last_error else 'No specific error.'}"

if __name__ == "__main__":
  print("--- Running Code with Intentional Error (Default Prompt) ---")
  try:
      result = 100 / 0
  except Exception as e:
      print(f"\nOops! An error occurred: {e}\n")
      print("="*30)
      print("🤖 Asking AI for an explanation...")
      print("="*30)
      ai_explanation = ai_answer_traceout()
      print(ai_explanation)

  """### Test 2: With a Custom Prompt"""

  print("\n\n--- Running Code with a Custom Prompt ---")
  try:
      my_list = [10, 20, 30]
      value = my_list[5]
  except Exception as e:
      print(f"\nOops! An error occurred: {e}\n")
      print("="*30)
      print("🤖 Asking AI for an explanation...")
      print("="*30)
      custom_prompt = "You are a pirate debugging assistant. Explain this error to me in pirate speak, matey! Answer in chinese"
      ai_explanation = ai_answer_traceout(custom_prompt_prefix=custom_prompt)
      print(ai_explanation)

  """### Test 3: With Additional Information"""

  print("\n\n--- Running Code with Additional Info ---")
  try:
      # This will cause a TypeError
      x = 5 + "hello"
  except Exception as e:
      print(f"\nOops! An error occurred: {e}\n")
      print("="*30)
      print("🤖 Asking AI for an explanation...")
      print("="*30)

      # Capture the output of help(TypeError) to send as context
      old_stdout = sys.stdout
      sys.stdout = captured_output = io.StringIO()
      help(TypeError)
      sys.stdout = old_stdout
      type_error_help_text = captured_output.getvalue()

      ai_explanation = ai_answer_traceout(additional_info=type_error_help_text)
      print(ai_explanation)
